export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  dir: 'ltr' | 'rtl';
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', dir: 'ltr', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl', flag: '🇦🇪' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', dir: 'ltr', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', dir: 'ltr', flag: '🇫🇷' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', dir: 'ltr', flag: '🇧🇷' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', dir: 'ltr', flag: '🇮🇳' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', dir: 'ltr', flag: '🇩🇪' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', dir: 'rtl', flag: '🇵🇰' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', dir: 'rtl', flag: '🇮🇱' },
  { code: 'fa', name: 'Persian / Farsi', nativeName: 'فارسی', dir: 'rtl', flag: '🇮🇷' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', dir: 'ltr', flag: '🇮🇩' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', dir: 'ltr', flag: '🇹🇷' },
];

export interface FormTranslations {
  welcomeMessageDefault: string;
  selectProducts: string;
  outOfStock: string;
  yourDetails: string;
  fullNameLabel: string;
  fullNamePlaceholder: string;
  phoneLabel: string;
  phonePlaceholder: string;
  phoneHelper: string;
  addressLabel: string;
  addressPlaceholder: string;
  fulfillmentTypeLabel: string;
  deliveryOption: string;
  pickupOption: string;
  streetLabel: string;
  streetPlaceholder: string;
  stateLabel: string;
  statePlaceholder: string;
  postalCodeLabel: string;
  postalCodePlaceholder: string;
  pickupAddressNote: string;
  orderSummary: string;
  orderTotal: string;
  itemsSelected: string;
  sendWhatsAppBtn: string;
  fillRequiredAlert: string;
  waGreeting: string;
  waTotal: string;
  waName: string;
  waPhone: string;
  waAddress: string;
  waFulfillment: string;
  waOrderDetails: string;
  paymentMethodsLabel: string;
  payWithStripe: string;
  payWithPayPal: string;
  payWithUPI: string;
  payWithWise: string;
  payWithSquare: string;
  copyUPI: string;
  upiCopied: string;
  paymentNoteLabel: string;
  receiptLanguageLabel: string;
  receiptStyleLabel: string;
}

export const TRANSLATIONS: Record<string, Partial<FormTranslations>> = {
  en: {
    welcomeMessageDefault: 'Welcome! Browse our products and place your order.',
    selectProducts: 'Select Items to Order',
    outOfStock: 'Out of Stock',
    yourDetails: 'Contact & Delivery Details',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Enter your full name *',
    phoneLabel: 'WhatsApp / Phone Number 📱',
    phonePlaceholder: 'Enter phone number',
    phoneHelper: 'In case the seller needs to contact you regarding delivery',
    addressLabel: 'Delivery Address',
    addressPlaceholder: 'Enter full delivery address',
    fulfillmentTypeLabel: 'Fulfillment Method 🚚',
    deliveryOption: 'Home Delivery 🚚',
    pickupOption: 'Local Pickup 🏪',
    streetLabel: 'Street / Building / House',
    streetPlaceholder: 'House/Flat No., Street Name, Building *',
    stateLabel: 'State / Province / Region',
    statePlaceholder: 'e.g. California, NY, Ontario',
    postalCodeLabel: 'ZIP / Postal Code',
    postalCodePlaceholder: 'e.g. 90210',
    pickupAddressNote: '📍 Local Pickup Selected — You can pick up directly from the store.',
    orderSummary: 'Order Summary',
    orderTotal: 'Order Total:',
    itemsSelected: 'item(s) selected',
    sendWhatsAppBtn: 'Send Order via WhatsApp',
    fillRequiredAlert: 'Please fill out all required fields!',
    waGreeting: 'Hello',
    waTotal: 'Total',
    waName: 'Name',
    waPhone: 'Phone',
    waAddress: 'Address',
    waFulfillment: 'Method',
    waOrderDetails: "I'd like to order:",
    paymentMethodsLabel: 'Payment Options 💳',
    payWithStripe: 'Pay with Stripe',
    payWithPayPal: 'Pay with PayPal',
    payWithUPI: 'Pay via UPI / QR',
    payWithWise: 'Pay via Wise',
    payWithSquare: 'Pay via Square',
    copyUPI: 'Copy UPI ID',
    upiCopied: 'UPI ID Copied! ✅',
    paymentNoteLabel: 'Payment Instructions:',
    receiptLanguageLabel: 'WhatsApp Message Language 🌐',
    receiptStyleLabel: 'Receipt Template Style 🧾',
  },
  ar: {
    welcomeMessageDefault: 'أهلاً بك! تصفح منتجاتنا وقدم طلبك الآن.',
    selectProducts: 'اختر المنتجات للطلب',
    outOfStock: 'نفد من المخزون',
    yourDetails: 'تفاصيل الاتصال والتوصيل',
    fullNameLabel: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل اسمك الكامل *',
    phoneLabel: 'رقم الواتساب / الهاتف 📱',
    phonePlaceholder: 'أدخل رقم الهاتف',
    phoneHelper: 'في حال احتاج البائع للتواصل معك بخصوص التوصيل',
    addressLabel: 'عنوان التوصيل',
    addressPlaceholder: 'أدخل عنوان التوصيل الكامل',
    fulfillmentTypeLabel: 'طريقة الاستلام 🚚',
    deliveryOption: 'توصيل للمنزل 🚚',
    pickupOption: 'استلام من المتجر 🏪',
    streetLabel: 'الشارع / المبنى / الشقة',
    streetPlaceholder: 'رقم الشقة، اسم الشارع، المبنى *',
    stateLabel: 'المنطقة / المحافظة / الولاية',
    statePlaceholder: 'مثال: الرياض، دبي، القاهرة',
    postalCodeLabel: 'الرمز البريدي',
    postalCodePlaceholder: 'مثال: 11564',
    pickupAddressNote: '📍 تم اختيار الاستلام من المتجر — يمكنك الاستلام مباشرة من الفرع.',
    orderSummary: 'ملخص الطلب',
    orderTotal: 'إجمالي الطلب:',
    itemsSelected: 'عنصر محدد',
    sendWhatsAppBtn: 'إرسال الطلب عبر الواتساب',
    fillRequiredAlert: 'يرجى ملء جميع الحقول المطلوبة!',
    waGreeting: 'مرحباً',
    waTotal: 'المجموع',
    waName: 'الاسم',
    waPhone: 'الهاتف',
    waAddress: 'العنوان',
    waFulfillment: 'طريقة الاستلام',
    waOrderDetails: 'أود طلب ما يلي:',
  },
  es: {
    welcomeMessageDefault: '¡Bienvenido! Revisa nuestros productos y realiza tu pedido.',
    selectProducts: 'Selecciona los productos para pedir',
    outOfStock: 'Agotado',
    yourDetails: 'Datos de contacto y entrega',
    fullNameLabel: 'Nombre completo',
    fullNamePlaceholder: 'Ingresa tu nombre completo *',
    phoneLabel: 'Número de WhatsApp / Teléfono 📱',
    phonePlaceholder: 'Ingresa tu teléfono',
    phoneHelper: 'Para que el vendedor te contacte sobre la entrega',
    addressLabel: 'Dirección de entrega',
    addressPlaceholder: 'Ingresa tu dirección completa',
    fulfillmentTypeLabel: 'Método de entrega 🚚',
    deliveryOption: 'Envío a domicilio 🚚',
    pickupOption: 'Recoger en tienda 🏪',
    streetLabel: 'Calle / Edificio / Número',
    streetPlaceholder: 'Nº de casa, calle, edificio *',
    stateLabel: 'Estado / Provincia / Región',
    statePlaceholder: 'ej. Madrid, CDMX, Buenos Aires',
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: 'ej. 28001',
    pickupAddressNote: '📍 Recogida en tienda seleccionada — Puedes pasar directamente por el local.',
    orderSummary: 'Resumen del pedido',
    orderTotal: 'Total del pedido:',
    itemsSelected: 'artículo(s) seleccionado(s)',
    sendWhatsAppBtn: 'Enviar pedido por WhatsApp',
    fillRequiredAlert: '¡Por favor completa todos los campos requeridos!',
    waGreeting: 'Hola',
    waTotal: 'Total',
    waName: 'Nombre',
    waPhone: 'Teléfono',
    waAddress: 'Dirección',
    waFulfillment: 'Método',
    waOrderDetails: 'Me gustaría pedir:',
  },
  fr: {
    welcomeMessageDefault: 'Bienvenue! Parcourez nos produits et passez votre commande.',
    selectProducts: 'Sélectionnez les articles à commander',
    outOfStock: 'Rupture de stock',
    yourDetails: 'Coordonnées & Livraison',
    fullNameLabel: 'Nom complet',
    fullNamePlaceholder: 'Entrez votre nom complet *',
    phoneLabel: 'Numéro WhatsApp / Téléphone 📱',
    phonePlaceholder: 'Entrez votre numéro',
    phoneHelper: 'Au cas où le vendeur aurait besoin de vous contacter',
    addressLabel: 'Adresse de livraison',
    addressPlaceholder: 'Entrez votre adresse complète',
    fulfillmentTypeLabel: 'Mode de livraison 🚚',
    deliveryOption: 'Livraison à domicile 🚚',
    pickupOption: 'Retrait en magasin 🏪',
    streetLabel: 'Rue / Bâtiment / Numéro',
    streetPlaceholder: 'Nº d appartement, rue, bâtiment *',
    stateLabel: 'Région / Département / Province',
    statePlaceholder: 'ex. Île-de-France, Québec',
    postalCodeLabel: 'Code postal',
    postalCodePlaceholder: 'ex. 75001',
    pickupAddressNote: '📍 Retrait en magasin sélectionné — Vous pouvez récupérer votre commande directement.',
    orderSummary: 'Récapitulatif de la commande',
    orderTotal: 'Total de la commande:',
    itemsSelected: 'article(s) sélectionné(s)',
    sendWhatsAppBtn: 'Envoyer la commande via WhatsApp',
    fillRequiredAlert: 'Veuillez remplir tous les champs obligatoires!',
    waGreeting: 'Bonjour',
    waTotal: 'Total',
    waName: 'Nom',
    waPhone: 'Téléphone',
    waAddress: 'Adresse',
    waFulfillment: 'Mode',
    waOrderDetails: 'Je souhaite commander:',
  },
  pt: {
    welcomeMessageDefault: 'Bem-vindo! Veja nossos produtos e faça seu pedido.',
    selectProducts: 'Selecione os itens para pedir',
    outOfStock: 'Fora de estoque',
    yourDetails: 'Dados de Contato e Entrega',
    fullNameLabel: 'Nome completo',
    fullNamePlaceholder: 'Digite seu nome completo *',
    phoneLabel: 'Número de WhatsApp / Telefone 📱',
    phonePlaceholder: 'Digite seu telefone',
    phoneHelper: 'Caso o vendedor precise entrar em contato sobre a entrega',
    addressLabel: 'Endereço de entrega',
    addressPlaceholder: 'Digite seu endereço completo',
    fulfillmentTypeLabel: 'Forma de Entrega 🚚',
    deliveryOption: 'Entrega em domicílio 🚚',
    pickupOption: 'Retirada na loja 🏪',
    streetLabel: 'Rua / Número / Bairro',
    streetPlaceholder: 'Rua, Número, Apto, Bairro *',
    stateLabel: 'Estado / Região',
    statePlaceholder: 'ex. SP, RJ, Lisboa',
    postalCodeLabel: 'CEP / Código Postal',
    postalCodePlaceholder: 'ex. 01000-000',
    pickupAddressNote: '📍 Retirada na loja selecionada — Você pode retirar diretamente na loja.',
    orderSummary: 'Resumo do pedido',
    orderTotal: 'Total do pedido:',
    itemsSelected: 'item(ns) selecionado(s)',
    sendWhatsAppBtn: 'Enviar pedido pelo WhatsApp',
    fillRequiredAlert: 'Por favor, preencha todos os campos obrigatórios!',
    waGreeting: 'Olá',
    waTotal: 'Total',
    waName: 'Nome',
    waPhone: 'Telefone',
    waAddress: 'Endereço',
    waFulfillment: 'Forma',
    waOrderDetails: 'Gostaria de pedir:',
  },
  hi: {
    welcomeMessageDefault: 'स्वागत है! हमारे उत्पादों को देखें और अपना ऑर्डर दें।',
    selectProducts: 'ऑर्डर करने के लिए आइटम चुनें',
    outOfStock: 'आउट ऑफ स्टॉक',
    yourDetails: 'संपर्क और डिलीवरी विवरण',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम दर्ज करें *',
    phoneLabel: 'व्हाट्सएप / फोन नंबर 📱',
    phonePlaceholder: 'फोन नंबर दर्ज करें',
    phoneHelper: 'यदि विक्रेता को डिलीवरी के संबंध में संपर्क करने की आवश्यकता हो',
    addressLabel: 'डिलीवरी का पता',
    addressPlaceholder: 'पूरा डिलीवरी पता दर्ज करें',
    fulfillmentTypeLabel: 'ऑर्डर डिलीवरी का तरीका 🚚',
    deliveryOption: 'होम डिलीवरी 🚚',
    pickupOption: 'दुकान से खुद लें (पिकअप) 🏪',
    streetLabel: 'مکان / मकान / सड़क / बिल्डिंग',
    streetPlaceholder: 'مکان नंबर, स्ट्रीट नाम, बिल्डिंग *',
    stateLabel: 'राज्य / प्रांत / क्षेत्र',
    statePlaceholder: 'जैसे: दिल्ली, महाराष्ट्र, यूपी',
    postalCodeLabel: 'पिन कोड / पोस्टल कोड',
    postalCodePlaceholder: 'जैसे: 110001',
    pickupAddressNote: '📍 स्टोर पिकअप चुना गया है — आप सीधे स्टोर से ऑर्डर ले सकते हैं।',
    orderSummary: 'ऑर्डर का विवरण',
    orderTotal: 'कुल योग:',
    itemsSelected: 'आइटम चुने गए',
    sendWhatsAppBtn: 'व्हाट्सएप पर ऑर्डर भेजें',
    fillRequiredAlert: 'कृपया सभी आवश्यक फ़ील्ड भरें!',
    waGreeting: 'नमस्ते',
    waTotal: 'कुल',
    waName: 'नाम',
    waPhone: 'फोन',
    waAddress: 'पता',
    waFulfillment: 'طریقہ',
    waOrderDetails: 'मैं ऑर्डर करना चाहता हूँ:',
  },
  de: {
    welcomeMessageDefault: 'Willkommen! Durchsuchen Sie unsere Produkte und bestellen Sie.',
    selectProducts: 'Artikel zur Bestellung auswählen',
    outOfStock: 'Ausverkauft',
    yourDetails: 'Kontakt & Lieferdetails',
    fullNameLabel: 'Vollständiger Name',
    fullNamePlaceholder: 'Geben Sie Ihren vollständigen Namen ein *',
    phoneLabel: 'WhatsApp / Telefonnummer 📱',
    phonePlaceholder: 'Telefonnummer eingeben',
    phoneHelper: 'Falls der Verkäufer Sie bezüglich der Lieferung kontaktieren muss',
    addressLabel: 'Lieferadresse',
    addressPlaceholder: 'Vollständige Lieferadresse eingeben',
    fulfillmentTypeLabel: 'Erfüllungsart 🚚',
    deliveryOption: 'Lieferung nach Hause 🚚',
    pickupOption: 'Abholung im Geschäft 🏪',
    streetLabel: 'Straße & Hausnummer',
    streetPlaceholder: 'Hausnummer, Gebäude, Straße *',
    stateLabel: 'Bundesland / Region',
    statePlaceholder: 'z.B. Bayern, NRW, Wien',
    postalCodeLabel: 'Postleitzahl (PLZ)',
    postalCodePlaceholder: 'z.B. 10115',
    pickupAddressNote: '📍 Selbstabholung gewählt — Abholung direkt im Geschäft.',
    orderSummary: 'Bestellübersicht',
    orderTotal: 'Gesamtsumme:',
    itemsSelected: 'Artikel ausgewählt',
    sendWhatsAppBtn: 'Bestellung über WhatsApp senden',
    fillRequiredAlert: 'Bitte füllen Sie alle erforderlichen Felder aus!',
    waGreeting: 'Hallo',
    waTotal: 'Gesamt',
    waName: 'Name',
    waPhone: 'Telefon',
    waAddress: 'Adresse',
    waFulfillment: 'Lieferart',
    waOrderDetails: 'Ich möchte Folgendes bestellen:',
  },
  ur: {
    welcomeMessageDefault: 'خوش آمدید! ہماری مصنوعات دیکھیں اور اپنا آرڈر دیں۔',
    selectProducts: 'آرڈر کرنے کے لیے اشیاء منتخب کریں',
    outOfStock: 'دستیاب نہیں ہے',
    yourDetails: 'آپ کی رابطہ اور ترسیل کی تفصیلات',
    fullNameLabel: 'پورا نام',
    fullNamePlaceholder: 'اپنا پورا نام درج کریں *',
    phoneLabel: 'واٹس ایپ / فون نمبر 📱',
    phonePlaceholder: 'فون نمبر درج کریں',
    phoneHelper: 'اگر بیچنے والے کو ترسیل کے سلسلے میں آپ سے رابطہ کرنے کی ضرورت ہو',
    addressLabel: 'ترسیل کا پتہ',
    addressPlaceholder: 'مکمل ترسیل کا پتہ درج کریں',
    fulfillmentTypeLabel: 'آرڈر کی قسم 🚚',
    deliveryOption: 'ہوم ڈیلیوری 🚚',
    pickupOption: 'خود وصول کریں (پک اپ) 🏪',
    streetLabel: 'گلی / مکان / بلڈنگ',
    streetPlaceholder: 'مکان نمبر، گلی، بلڈنگ *',
    stateLabel: 'صوبہ / علاقہ',
    statePlaceholder: 'مثلاً: پنجاب، سندھ',
    postalCodeLabel: 'پوسٹل کوڈ',
    postalCodePlaceholder: 'مثلاً: 54000',
    pickupAddressNote: '📍 پک اپ منتخب کیا گیا — آپ دکان سے خود اپنا سامان لے سکتے ہیں۔',
    orderSummary: 'آرڈر کا خلاصہ',
    orderTotal: 'کل رقم:',
    itemsSelected: 'اشیاء منتخب کی گئیں',
    sendWhatsAppBtn: 'واٹس ایپ کے ذریعے آرڈر بھیجیں',
    fillRequiredAlert: 'براہ کرم تمام ضروری تفصیلات درج کریں!',
    waGreeting: 'السلام علیکم',
    waTotal: 'کل',
    waName: 'نام',
    waPhone: 'فون',
    waAddress: 'پتہ',
    waFulfillment: 'طریقہ',
    waOrderDetails: 'میں درج ذیل کا آرڈر دینا چاہتا ہوں:',
  },
  he: {
    welcomeMessageDefault: 'ברוכים הבאים! עיינו במוצרים שלנו ובצעו את ההזמנה שלכם.',
    selectProducts: 'בחר פריטים להזמנה',
    outOfStock: 'אזל מהמלאי',
    yourDetails: 'פרטי התקשרות ומשלוח',
    fullNameLabel: 'שם מלא',
    fullNamePlaceholder: 'הזן את שמך המלא *',
    phoneLabel: 'מספר וואטסאפ / טלפון 📱',
    phonePlaceholder: 'הזן מספר טלפון',
    phoneHelper: 'במקרה שהמוכר צריך ליצור איתך קשר לגבי המשلوח',
    addressLabel: 'כתובת למשלוח',
    addressPlaceholder: 'הזן כתובת מלאה',
    fulfillmentTypeLabel: 'אופן קבלת ההזמנה 🚚',
    deliveryOption: 'משלוח עד הבית 🚚',
    pickupOption: 'איסוף עצמי מהחנות 🏪',
    streetLabel: 'רחוב / منزل / מס’ בית',
    streetPlaceholder: 'מספר בית, רחוב, דירה *',
    stateLabel: 'מחוז / אזור',
    statePlaceholder: 'למשל: תל אביב, מרכז',
    postalCodeLabel: 'מיקוד',
    postalCodePlaceholder: 'למשל: 61000',
    pickupAddressNote: '📍 נבחר איסוף עצמי — ניתן לאסוף ישירות מהחנות.',
    orderSummary: 'סיכום הזמנה',
    orderTotal: 'סה"כ להזמנה:',
    itemsSelected: 'פריטים שנבחרו',
    sendWhatsAppBtn: 'שלח הזמנה בוואטסאפ',
    fillRequiredAlert: 'אנא מלא את כל שדות החובה!',
    waGreeting: 'שלום',
    waTotal: 'סה"כ',
    waName: 'שם',
    waPhone: 'טלפון',
    waAddress: 'כתובת',
    waFulfillment: 'שיטת קבלה',
    waOrderDetails: 'אני מעוניין להזמין:',
  },
  fa: {
    welcomeMessageDefault: 'خوش آمدید! محصولات ما را مرور کرده و سفارش خود را ثبت کنید.',
    selectProducts: 'انتخاب کالاها برای سفارش',
    outOfStock: 'ناموجود',
    yourDetails: 'اطلاعات تماس و تحویل',
    fullNameLabel: 'نام و نام خانوادگی',
    fullNamePlaceholder: 'نام کامل خود را وارد کنید *',
    phoneLabel: 'شماره واتساپ / تلفن 📱',
    phonePlaceholder: 'شماره تلفن را وارد کنید',
    phoneHelper: 'در صورتی که فروشنده نیاز به تماس با شما درباره تحویل داشته باشد',
    addressLabel: 'آدرس تحویل',
    addressPlaceholder: 'آدرس کامل تحویل را وارد کنید',
    fulfillmentTypeLabel: 'روش تحویل 🚚',
    deliveryOption: 'تحویل درب منزل 🚚',
    pickupOption: 'تحویل حضوری از فروشگاه 🏪',
    streetLabel: 'خیابان و پلاک',
    streetPlaceholder: 'پلاک، واحد، نام خیابان *',
    stateLabel: 'استان / منطقه',
    statePlaceholder: 'مثلا: تهران، اصفهان',
    postalCodeLabel: 'کد پستی',
    postalCodePlaceholder: 'مثلا: 1234567890',
    pickupAddressNote: '📍 تحویل حضوری انتخاب شد — می‌توانید مستقیماً از فروشگاه دریافت کنید.',
    orderSummary: 'خلاصه سفارش',
    orderTotal: 'مجموع سفارش:',
    itemsSelected: 'کالا انتخاب شده',
    sendWhatsAppBtn: 'ارسال سفارش از طریق واتساپ',
    fillRequiredAlert: 'لطفا تمام اطلاعات لازم را وارد کنید!',
    waGreeting: 'سلام',
    waTotal: 'مجموع',
    waName: 'نام',
    waPhone: 'تلفن',
    waAddress: 'آدرس',
    waFulfillment: 'روش تحویل',
    waOrderDetails: 'من می‌خواهم سفارش دهم:',
  },
  id: {
    welcomeMessageDefault: 'Selamat datang! Lihat produk kami dan buat pesanan Anda.',
    selectProducts: 'Pilih produk untuk dipesan',
    outOfStock: 'Stok Habis',
    yourDetails: 'Detail Kontak & Pengiriman',
    fullNameLabel: 'Nama Lengkap',
    fullNamePlaceholder: 'Masukkan nama lengkap Anda *',
    phoneLabel: 'Nomor WhatsApp / Telepon 📱',
    phonePlaceholder: 'Masukkan nomor telepon',
    phoneHelper: 'Jika penjual perlu menghubungi Anda mengenai pengiriman',
    addressLabel: 'Alamat Pengiriman',
    addressPlaceholder: 'Masukkan alamat pengiriman lengkap',
    fulfillmentTypeLabel: 'Metode Pesanan 🚚',
    deliveryOption: 'Pengiriman ke Rumah 🚚',
    pickupOption: 'Ambil di Toko 🏪',
    streetLabel: 'Alamat / Jalan / Bangunan',
    streetPlaceholder: 'No. Rumah, Gedung, Nama Jalan *',
    stateLabel: 'Provinsi / Wilayah',
    statePlaceholder: 'misal: DKI Jakarta, Jawa Barat',
    postalCodeLabel: 'Kode Pos',
    postalCodePlaceholder: 'misal: 10110',
    pickupAddressNote: '📍 Ambil di Toko dipilih — Anda dapat mengambil langsung di toko.',
    orderSummary: 'Ringkasan Pesanan',
    orderTotal: 'Total Pesanan:',
    itemsSelected: 'item dipilih',
    sendWhatsAppBtn: 'Kirim Pesanan via WhatsApp',
    fillRequiredAlert: 'Silakan lengkapi semua data yang diperlukan!',
    waGreeting: 'Halo',
    waTotal: 'Total',
    waName: 'Nama',
    waPhone: 'Telepon',
    waAddress: 'Alamat',
    waFulfillment: 'Metode',
    waOrderDetails: 'Saya ingin memesan:',
  },
  tr: {
    welcomeMessageDefault: 'Hoş geldiniz! Ürünlerimize göz atın ve siparişinizi verin.',
    selectProducts: 'Sipariş verilecek ürünleri seçin',
    outOfStock: 'Stokta Yok',
    yourDetails: 'İletişim ve Teslimat Bilgileri',
    fullNameLabel: 'Ad Soyad',
    fullNamePlaceholder: 'Adınızı ve soyadınızı girin *',
    phoneLabel: 'WhatsApp / Telefon Numarası 📱',
    phonePlaceholder: 'Telefon numaranızı girin',
    phoneHelper: 'Satıcının teslimat için sizinle iletişime geçmesi gerekirse',
    addressLabel: 'Teslimat Adresi',
    addressPlaceholder: 'Açık teslimat adresinizi girin',
    fulfillmentTypeLabel: 'Teslimat Yöntemi 🚚',
    deliveryOption: 'Adrese Teslimat 🚚',
    pickupOption: 'Mağazadan Teslim Al 🏪',
    streetLabel: 'Sokak / Bina / Daire',
    streetPlaceholder: 'Bina No, Daire, Sokak adı *',
    stateLabel: 'İl / İlçe / Bölge',
    statePlaceholder: 'ör. İstanbul, Ankara, İzmir',
    postalCodeLabel: 'Posta Kodu',
    postalCodePlaceholder: 'ör. 34000',
    pickupAddressNote: '📍 Mağazadan Teslim seçildi — Doğrudan mağazadan alabilirsiniz.',
    orderSummary: 'Sipariş Özeti',
    orderTotal: 'Sipariş Toplamı:',
    itemsSelected: 'ürün seçildi',
    sendWhatsAppBtn: 'Siparişi WhatsApp ile Gönder',
    fillRequiredAlert: 'Lütfen gerekli tüm bilgileri doldurun!',
    waGreeting: 'Merhaba',
    waTotal: 'Toplam',
    waName: 'Ad',
    waPhone: 'Telefon',
    waAddress: 'Adres',
    waFulfillment: 'Teslimat',
    waOrderDetails: 'Şu ürünleri sipariş etmek istiyorum:',
  },
};

export function getLanguageConfig(langCode?: string): LanguageOption {
  if (!langCode) return LANGUAGES[0];
  const found = LANGUAGES.find(l => l.code.toLowerCase() === langCode.toLowerCase());
  return found || LANGUAGES[0];
}

export function getTranslations(langCode?: string): FormTranslations {
  const defaultEn = TRANSLATIONS.en as FormTranslations;
  if (!langCode) return defaultEn;
  const found = TRANSLATIONS[langCode.toLowerCase()];
  if (!found) return defaultEn;
  return { ...defaultEn, ...found } as FormTranslations;
}

export function isRTL(langCode?: string): boolean {
  const config = getLanguageConfig(langCode);
  return config.dir === 'rtl';
}
